cache: cargo
dist: trusty
env: TARGET=x86_64-unknown-linux-gnu
language: rust
services: docker
sudo: required

rust:
  - stable
  - nightly

script:
  - bash generate-tests.sh
  - cargo generate-lockfile
  - sh ci/run-docker.sh $TARGET
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - auto
    - try

notifications:
  email:
    on_success: never
